version: '3'

services:
  test:
    image: mysql:5.7
    build: ./docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: murmurDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: Asia/Dhaka
    restart: always
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306
    security_opt:
      - seccomp:unconfined
volumes:
  data:
